- hosts: node1
  tasks:


          - name: installing httpd
            package:
                    name: httpd
                    state: present

          - name: creating the index.php page
            copy:
                    content: '<?php
                              echo "hello world";
                              ?>'
                    dest: /var/www/html/index.php
      

          - name: adding a conf file
            template:
                    dest: /etc/httpd/conf.d/abc.conf
                    src: conffile
            notify: restarting httpd service

          - name: 'stop firewalld'
            service:
                    name: firewalld
                    state: stopped

          - name: enabling SELinux
            selinux:
                    policy: targeted
                    state: permissive
                    

  handlers:
          
          - name: restarting httpd service
            service:
                  name:  httpd
                  state: restarted


